import { Input, InputGroup, InputLeftElement } from '@chakra-ui/react'
import { SearchIcon } from '@chakra-ui/icons'
import { useCanvasContext } from '@/components/Canvas/hooks'
const template = {
  "version": "5.2.1",
  "objects": [
    {
      "type": "image",
      "version": "5.2.1",
      "originX": "left",
      "originY": "top",
      "left": 422,
      "top": 151,
      "width": 720,
      "height": 1080,
      "fill": "rgb(0,0,0)",
      "stroke": null,
      "strokeWidth": 0,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": false,
      "strokeMiterLimit": 4,
      "scaleX": 0.2,
      "scaleY": 0.2,
      "angle": 2,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "cropX": 0,
      "cropY": 0,
      "src": "http://fabricjs.com/assets/pug.jpg",
      "crossOrigin": "anonymous",
      "filters": []
    },
    {
      "type": "rect",
      "version": "5.2.1",
      "originX": "left",
      "originY": "top",
      "left": 128,
      "top": 77,
      "width": 50,
      "height": 50,
      "fill": "#e7da8a",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": false,
      "strokeMiterLimit": 4,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 0.8,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "rx": 0,
      "ry": 0
    },
    {
      "type": "text",
      "version": "5.2.1",
      "originX": "left",
      "originY": "top",
      "left": 67,
      "top": 295,
      "width": 598.13,
      "height": 307.36,
      "fill": "#39a422",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": false,
      "strokeMiterLimit": 4,
      "scaleX": 0.5,
      "scaleY": 0.5,
      "angle": 8,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "fontFamily": "helvetica",
      "fontWeight": "",
      "fontSize": 40,
      "text": "Lorem ipsum dolor sit amet,\nconsectetur adipisicing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore magna aliqua.\nUt enim ad minim veniam,\nquis nostr",
      "underline": false,
      "overline": false,
      "linethrough": false,
      "textAlign": "left",
      "fontStyle": "normal",
      "lineHeight": 1.16,
      "textBackgroundColor": "",
      "charSpacing": 0,
      "styles": [],
      "direction": "ltr",
      "path": null,
      "pathStartOffset": 0,
      "pathSide": "left",
      "pathAlign": "baseline"
    }
  ]
}

const template2 = {
  "version": "5.2.1",
  "objects": [
    {
      "type": "image",
      "version": "5.2.1",
      "originX": "left",
      "originY": "top",
      "left": 70.89,
      "top": 75.42,
      "width": 720,
      "height": 1080,
      "fill": "rgb(0,0,0)",
      "stroke": null,
      "strokeWidth": 0,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": false,
      "strokeMiterLimit": 4,
      "scaleX": 0.22,
      "scaleY": 0.22,
      "angle": 359.13,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "cropX": 0,
      "cropY": 0,
      "src": "http://fabricjs.com/assets/pug.jpg",
      "crossOrigin": "anonymous",
      "filters": []
    },
    {
      "type": "i-text",
      "version": "5.2.1",
      "originX": "left",
      "originY": "top",
      "left": 357.7,
      "top": 154.61,
      "width": 371.25,
      "height": 45.2,
      "fill": "#030500",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": false,
      "strokeMiterLimit": 4,
      "scaleX": 0.56,
      "scaleY": 0.56,
      "angle": 359.17,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "fontFamily": "helvetica",
      "fontWeight": "",
      "fontSize": 40,
      "text": "Lorem ipsum dolor si",
      "underline": false,
      "overline": false,
      "linethrough": false,
      "textAlign": "left",
      "fontStyle": "normal",
      "lineHeight": 1.16,
      "textBackgroundColor": "",
      "charSpacing": 0,
      "styles": [],
      "direction": "ltr",
      "path": null,
      "pathStartOffset": 0,
      "pathSide": "left",
      "pathAlign": "baseline"
    },
    {
      "type": "rect",
      "version": "5.2.1",
      "originX": "left",
      "originY": "top",
      "left": 382.68,
      "top": 282.2,
      "width": 300,
      "height": 300,
      "fill": {
        "type": "pattern",
        "source": "http://fabricjs.com/assets/ladybug.png",
        "repeat": "repeat",
        "crossOrigin": "",
        "offsetX": 0,
        "offsetY": 0,
        "patternTransform": null
      },
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": false,
      "strokeMiterLimit": 4,
      "scaleX": 0.82,
      "scaleY": 0.82,
      "angle": 5,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "rx": 0,
      "ry": 0
    }
  ]
}

function TemplatesPanel() {
  const { canvas } = useCanvasContext()

  const load = (t) => {
    canvas.loadFromJSON(t, function () {
      canvas.renderAll();
    });
  }
  return (
    <>
      <div style={{ padding: '1rem 2rem' }}>
        <InputGroup>
          <InputLeftElement pointerEvents="none" children={<SearchIcon color="gray.300" />} />
          <Input style={{ background: '#fff' }} type="tel" placeholder="Search templates" />
        </InputGroup>
        <button onClick={() => load(template)} style={{color: 'white'}}>load template</button>
        <button onClick={() => load(template2)}style={{color: 'white'}} >load template2</button>
      </div>
    </>
  )
}
export default TemplatesPanel
